version: '3.1'

services:
  mongodb:
    build: .
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=todoapp
      - MONGO_REPLICA_HOST=localhost
      - MONGO_REPLICA_PORT=27017
    ports:
      - "27017:27017"

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DATABASE_URL=mongodb://root:example@mongodb:27017/todoapp?authSource=admin&directConnection=true
  #     - PORT=8080
  #   depends_on:
  #     - mongodb
  #   restart: always

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #   - API_BASE_URL=http://backend:8080/api
  #   depends_on:
  #     - backend
  #   restart: always
  